#!/bin/sh
#
# x11keysyms.sh - generate x11keysyms.h from the X11 keysym definitions.
#
# The headless UI has no toolkit to ask for a keysym number, but VICE's shipped
# keymaps (data/*/gtk3_*.vkm) name their keys with X11 keysym names. This turns
# X11's own keysymdef.h into a name<->number table so the headless build can
# load those keymaps unchanged. Mechanical, never hand-edited: same rule as
# gdkkeysyms.sh next door.
#
# usage: ./x11keysyms.sh [/usr/include/X11/keysymdef.h] > x11keysyms.h
#
# This file is part of VICE, the Versatile Commodore Emulator.
# See README for copyright notice.

SRC="${1:-/usr/include/X11/keysymdef.h}"

if [ ! -f "$SRC" ]; then
    echo "x11keysyms.sh: $SRC not found (install x11proto-dev / xorgproto)" >&2
    exit 1
fi

cat <<'EOF'
/* x11keysyms.h - GENERATED by x11keysyms.sh from X11/keysymdef.h. Do not edit.
 *
 * This file is part of VICE, the Versatile Commodore Emulator.
 * See README for copyright notice.
 */

#ifndef VICE_HEADLESS_X11KEYSYMS_H
#define VICE_HEADLESS_X11KEYSYMS_H

typedef struct {
    const char *name;
    signed long sym;
} x11_keysym_t;

static const x11_keysym_t x11_keysyms[] = {
EOF

sed -n 's/^#define XK_\([A-Za-z0-9_]*\)  *0x\([0-9a-fA-F]*\).*/    { "\1", 0x\2 },/p' "$SRC"

cat <<'EOF'
    { NULL, 0 }
};

#endif
EOF
